// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcpmgr$0 from "../../pkg/mcpmgr/models.js";

/**
 * SerializedServerConfig provides a transport-agnostic view of a ServerConfig.
 */
export class SerializedServerConfig {
    "type": string;
    "command"?: string;
    "args"?: string[];
    "env"?: { [_: string]: string };
    "endpoint"?: string;
    "maxRetries"?: number | null;
    "sessionId"?: string;
    "preferSse"?: boolean | null;
    "timeoutSeconds": number;
    "version"?: string;
    "logJsonRpc": boolean;

    /** Creates a new SerializedServerConfig instance. */
    constructor($$source: Partial<SerializedServerConfig> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("timeoutSeconds" in $$source)) {
            this["timeoutSeconds"] = 0;
        }
        if (!("logJsonRpc" in $$source)) {
            this["logJsonRpc"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerializedServerConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SerializedServerConfig {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField2_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField3_0($$parsedSource["env"]);
        }
        return new SerializedServerConfig($$parsedSource as Partial<SerializedServerConfig>);
    }
}

/**
 * SerializedServerSummary exposes a JSON-friendly representation of the manager's
 * ServerSummary for UI consumption.
 */
export class SerializedServerSummary {
    "id": string;
    "status": mcpmgr$0.ConnectionStatus;
    "config"?: SerializedServerConfig | null;

    /** Creates a new SerializedServerSummary instance. */
    constructor($$source: Partial<SerializedServerSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = mcpmgr$0.ConnectionStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerializedServerSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SerializedServerSummary {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new SerializedServerSummary($$parsedSource as Partial<SerializedServerSummary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = SerializedServerConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
